name: 2 create_branch

## ブランチを作って、コミットを行い、PRを作るまでの一連の作業を担う
## 初期制作 ghを用いた他での制作も並行しているが同時にブラッシュアップしている
## コミットは難しいようだ。


on:
  workflow_call:
    inputs:
      datetime:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:

  build_create_new_branch_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17 ]

    steps:
      - name: Create new branch
        run: |
          
          ### 表示デバッグ
          echo "${{ env.action_state }}" # This will output 'yellow'
          echo "secrets.githubtoken is " ${{ secrets.GITHUB_TOKEN }}
          echo "github actor is" ${{ env.GITHUB_ACTOR }}
          echo "github repository is" ${{ github.event.repository.name}}
          
          
          git remote set-url origin https://github-actions:${{GITHUB_TOKEN}}@github.com/${{github.event.repository.name}}
          
          ### Gitユーザの設定を行う
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          
          ### 対象のレポジトリを取り込む
          gh repo clone miquolone/test_actions
          cd test_actions
          
          ### ブランチ名を指定
          
          ### 当日の日付でブランチを作る
          git switch -c release/ABC_${{ env.CURRENT_DATETIME }}_first_v3
          
          ### 空のコミットだけpushしておく
          git add -A && git commit -m 'make it release' --allow-empty
          
          ### git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/test_actions.git" gh-pages
          git config -l
          
          echo "$GITHUB_CONTEXT"
          
          ## git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          ## git remote set-url origin git@github.com:miquolone/test_actions.git
          
          git remote set-url origin https://miquolone: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@github.com/miquolone/test_actions
          
          
          git push -u origin release/ABC_${{ env.CURRENT_DATETIME }}_first_v3
          
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/test_actions.git" release/ABC_${{ env.CURRENT_DATETIME }}_first_v3
          echo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/test_actions.git"

          ### リリースは作らなくていいかもしれない
          gh release create ${{env.CURRENT_DATETIME }}_v3 README.md

        shell: bash

        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_ACTOR: 'miquolone'
          CURRENT_DATETIME: ${{ inputs.datetime }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator

      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"


      - name: Create new branch Type 2
        run: |
          gh repo clone miquolone/test_actions
          cd test_actions
          git config --global user.name "Mona Lisa"
          git switch -c release/ABC_${{ env.CURRENT_DATETIME }}_second
          git branch -a
          git config -l
          git push origin release/ABC_${{ env.CURRENT_DATETIME }}_second
        env:
          CURRENT_DATETIME: ${{ inputs.datetime }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ssh-keygen -t rsa -f ~/.ssh/id_rsa_gitHub -q -N github_pass_phrase_aiueo
      # ls ~/.ssh/
      # echo ~/.git/config
      # git rm --cached test
      # git clone https://miquolone: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@github.com/miquolone/test
      # cd test
      # git remote set-url origin https://miquolone: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@github.com/miquolone/test
      # git clone https://${env.GITHUB_ACTOR}:${GIT_TOKEN}@github.com/${GIT_REPOSITORY}
      # git config --global user.name '${{env.GITHUB_ACTOR}}'
      # git config --global user.email '${{env.GITHUB_ACTOR}}@users.noreply.github.com'
      # git config -l
      # git branch -a
      # ssh-keygen -t rsa -f ~/.ssh/id_rsa_gitHub -q -N github_pass_phrase_aiueo
      # ssh -T git@github.com
      #git remote add origin git@github.com:miquolone/test.git
#        env:
#          GIT_REPOSITORY: 'miquolone/test'
