# コミットするだけ


name: 3 add commit data

on:
  workflow_call:
    inputs:
      datetime:
        required: true
        type: string

jobs:

  run_gh_command:
    runs-on: ubuntu-latest
    steps:
      #- name: Enable auto-merge for new PRs
      #  run: gh pr merge --auto --merge "$PR_URL"
      #  env:
      #    PR_URL: ${{github.event.pull_request.html_url}}
      #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Clone repo and Create a release and attach files
        run: |
          gh repo clone miquolone/test_actions
          cd test_actions
          # tagname="${GITHUB_REF#refs/tags/}"
          echo ${{ inputs.datetime }}
          echo "ghによるリリース作成"
          gh release create ${{env.branch}} README.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          branch: release/ABC_${{ inputs.datetime }}_maked_blank_v3

  build:
    needs:
      - run_gh_command
    runs-on: ubuntu-latest
    steps:

      - name: checkout [ checkout@v3を使ったclone処理 ]
        uses: actions/checkout@v4

      - name: show time [ callもとで作成している時間の表示 ]
        run: echo "time is::${{inputs.datetime}}"

      - name: Add and Commit [commitを追加する]
        uses: EndBug/add-and-commit@v9
        env:
          PR_TITLE: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/ABC_${{ inputs.datetime }}_maked_blank_v3
          message: ${{ env.PR_TITLE }}


      ### この段階で指定ブランチができている必要がある
      - name: Create PR [プルリクエストを作る]
        id: open-pr
        env:
          PR_LABEL: ${inputs.datetime}_PullRequest
          DEST_BRANCH: "main"
          branch: release/ABC_${{ inputs.datetime }}_maked_blank_v3
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.branch }}
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: ${{ env.PR_TITLE }}
          pr_template: ${{ env.PR_TEMPLATE }}
          pr_label: ${{ env.PR_LABEL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: "miquolone"
          pr_assignee: "miquolone"
          pr_milestone: ""
          pr_draft: true
          pr_allow_empty: true


      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
      - name: output-has-changed-files
        run: echo ${{steps.open-pr.outputs.has_changed_files}}


      - name: show env.se
        run: |
          echo ${{ secrets.KEY }}
          echo ${{ secrets.actions}}
          echo "$SUPER_SECRET"
          echo Hello, world!
        env:
          SUPER_SECRET: ${{ secrets.KEY }}
