# コミットするだけ


name: CI_COMMIT

on:
  workflow_call:
    inputs:
      datetime:
        required: true
        type: string
      username:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:

  run_gh_command:
    runs-on: ubuntu-latest
    steps:
      #- name: Enable auto-merge for new PRs
      #  run: gh pr merge --auto --merge "$PR_URL"
      #  env:
      #    PR_URL: ${{github.event.pull_request.html_url}}
      #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Clone repo and Create a release and attach files
        run: |
          gh repo clone miquolone/test_actions
          cd test_actions
          # tagname="${GITHUB_REF#refs/tags/}"
          echo ${{ inputs.datetime }}
          echo "ghによるリリース作成"
          gh release create ${{env.branch}}_v3 README.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          branch: release/ABC_${{ inputs.datetime }}

  build:
    needs:
      - run_gh_command
    runs-on: ubuntu-latest
    steps:
      - name: show time
        run: echo "time is::${{inputs.datetime}}"

      - uses: actions/checkout@v2
      - name: Add and Commit [commitを追加する]
        uses: EndBug/add-and-commit@v7
        env:
          PR_TITLE: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/ABC_${{ inputs.datetime }}
          message: ${{ env.PR_TITLE }}

      - name: Create pull request [プルリクエストを作る]
        env:
          PR_LABEL: ${inputs.datetime}_PullRequest
          DEST_BRANCH: "main"
        uses: repo-sync/pull-request@v2
        with:
          ### 多分この段階でfirst_v3ができていない
          source_branch: release/ABC_${{ inputs.datetime }}_first_v3
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: ${{ env.PR_TITLE }}
          pr_template: ${{ env.PR_TEMPLATE }}
          pr_label: ${{ env.PR_LABEL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: "miquolone"
          pr_assignee: "miquolone"
          pr_milestone: ""
          pr_draft: false
          pr_allow_empty: true

      - name: show env.se
        run: |
          echo ${{ secrets.KEY }}
          echo ${{ secrets.actions}}
          echo "$SUPER_SECRET"
          echo Hello, world!
        env:
          SUPER_SECRET: ${{ secrets.KEY }}
