# コミットするだけ


name: CI_D

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17, 16 ]

    steps:
      - name: Add and Commit [commitを追加する]
        uses: EndBug/add-and-commit@v7
        env:
          PR_TITLE: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/ABC_${{ env.CURRENT_DATETIME }}
          message: ${{ env.PR_TITLE }}

      - name: Create pull request [プルリクエストを作る]
        env:
          PR_LABEL: "aaaaaaaaa"
          DEST_BRANCH: "main"
        uses: repo-sync/pull-request@v2
        with:
          source_branch: release/ABC_${{ env.CURRENT_DATETIME }}_first
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: ${{ env.PR_TITLE }}
          pr_template: ${{ env.PR_TEMPLATE }}
          pr_label: ${{ env.PR_LABEL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: "miquolone"
          pr_assignee: "miquolone"
          pr_milestone: ""
          pr_draft: false
          pr_allow_empty: true

      - name: show env.se
        run: |
          echo ${{ secrets.KEY }}
          echo ${{ secrets.actions}}
          echo "$SUPER_SECRET"
          echo Hello, world!
        env:
          SUPER_SECRET: ${{ secrets.KEY }}
