# コミットするだけ


name: CI_COMMIT

on:
  workflow_call:
    inputs:
      datetime:
        required: true
        type: string
      username:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: show time
        run: echo "time is::${{inputs.datetime}}"

      - uses: actions/checkout@v2
      - name: Add and Commit [commitを追加する]
        uses: EndBug/add-and-commit@v7
        env:
          PR_TITLE: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/ABC_${{ inputs.datetime }}
          message: ${{ env.PR_TITLE }}

      - name: Create pull request [プルリクエストを作る]
        env:
          PR_LABEL: ${inputs.datetime}_PullRequest
          DEST_BRANCH: "main"
        uses: repo-sync/pull-request@v2
        with:
          source_branch: release/ABC_${{ inputs.datetime }}_v2
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: ${{ env.PR_TITLE }}
          pr_template: ${{ env.PR_TEMPLATE }}
          pr_label: ${{ env.PR_LABEL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: "miquolone"
          pr_assignee: "miquolone"
          pr_milestone: ""
          pr_draft: false
          pr_allow_empty: true

      - name: show env.se
        run: |
          echo ${{ secrets.KEY }}
          echo ${{ secrets.actions}}
          echo "$SUPER_SECRET"
          echo Hello, world!
        env:
          SUPER_SECRET: ${{ secrets.KEY }}
