# This is a basic workflow to help you get started with Actions




name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '*/3 * * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      node-version:
        description: 'node-version'
        required: true
        default: '16'
        type: choice
        options:
          - "12"
          - "14"
          - "16"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.print_tags == 'true' }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tag is ${{ github.event.inputs.tag }}

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12, 14, 16, 17 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
          persist-credentials: false


      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c fix/hoge_${{ env.CURRENT_DATETIME }}
          git push -u origin fix/hoge_${{ env.CURRENT_DATETIME }}


      - name: show env.se
        run: echo ${{ secrets.KEY }}

      - name: show env.actions
        run: echo ${{ secrets.actions}}

      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.KEY }}
        run: |
          echo "$SUPER_SECRET"
          git clone git@github.com:miquolone/test.git


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
