# This is a basic workflow to help you get started with Actions


name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      node-version:
        description: 'node-version'
        required: true
        default: '16'
        type: choice
        options:
          - "12"
          - "14"
          - "16"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node }}
          persist-credentials: true
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - run: |
          set -x
          assets=()
          for asset in ./*.md; do
            assets+=("-a" "$asset")
          done
          tag_name="${CURRENT_DATETIME}${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -pm "$tag_name" "$tag_name"
          echo "::group::My title"
          echo "::workflow-command parameter1={data},parameter2={data}::{command value}"
          echo "::endgroup::"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  example_jobA1:
    name: link to 1
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/print-tag.yml
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.token }}

      - uses: ./.github/workflows/print-tag
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.token }}


  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17, 16 ]

    steps:
      - name: Add and Commit [commitを追加する]
        uses: EndBug/add-and-commit@v7
        env:
          PR_TITLE: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release/ABC_${{ env.CURRENT_DATETIME }}
          message: ${{ env.PR_TITLE }}

      - name: Create pull request [プルリクエストを作る]
        env:
          PR_LABEL: "aaaaaaaaa"
          DEST_BRANCH: "main"
        uses: repo-sync/pull-request@v2
        with:
          source_branch: release/ABC_${{ env.CURRENT_DATETIME }}_first
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: ${{ env.PR_TITLE }}
          pr_template: ${{ env.PR_TEMPLATE }}
          pr_label: ${{ env.PR_LABEL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: "miquolone"
          pr_assignee: "miquolone"
          pr_milestone: ""
          pr_draft: false
          pr_allow_empty: true

      - name: show env.se
        run: |
          echo ${{ secrets.KEY }}
          echo ${{ secrets.actions}}
          echo "$SUPER_SECRET"
          echo Hello, world!
        env:
          SUPER_SECRET: ${{ secrets.KEY }}
