name: CI_CREATE_BRANCH

## ブランチを作って、コミットを行い、PRを作るまでの一連の作業を担う
## 初期制作 ghを用いた他での制作も並行しているが同時にブラッシュアップしている

on:
  workflow_call:
    inputs:
      datetime:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:

  build_create_new_branch_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17 ]

    steps:
      - name: Create new branch
        run: |
          echo "secrets.githubtoken is " ${{ secrets.GITHUB_TOKEN }}
          echo "github actor is" ${{ env.GITHUB_ACTOR}}
          echo "github actor is" ${{ GITHUB_ACTOR }}
          echo "github actor is" ${ GITHUB_ACTOR }
          echo "github actor is" $GITHUB_ACTOR
          
          git config --global user.name '${{env.GITHUB_ACTOR}}'
          git config --global user.email '${{env.GITHUB_ACTOR}}@users.noreply.github.com'
          
          gh repo clone miquolone/test_actions
          cd test_actions
          
          git switch -c release/ABC_${{ env.CURRENT_DATETIME }}_first_v3
          git add -A && git commit -m 'abc' --allow-empty
          git push origin release/ABC_${{ env.CURRENT_DATETIME }}_first_v3
          gh release create ${{env.CURRENT_DATETIME }}_v3 README.md

        env:
          CURRENT_DATETIME: ${{ inputs.datetime }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new branch Type 2
        run: |
          gh repo clone miquolone/test_actions
          cd test_actions
          git config --global user.name "Mona Lisa"
          git switch -c release/ABC_${{ env.CURRENT_DATETIME }}_second
          git branch -a
          git config -l
          git push origin release/ABC_${{ env.CURRENT_DATETIME }}_second
        env:
          CURRENT_DATETIME: ${{ inputs.datetime }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ssh-keygen -t rsa -f ~/.ssh/id_rsa_gitHub -q -N github_pass_phrase_aiueo
      # ls ~/.ssh/
      # echo ~/.git/config
      # git rm --cached test
      # git clone https://miquolone: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@github.com/miquolone/test
      # cd test
      # git remote set-url origin https://miquolone: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@github.com/miquolone/test
      # git clone https://${env.GITHUB_ACTOR}:${GIT_TOKEN}@github.com/${GIT_REPOSITORY}
      # git config --global user.name '${{env.GITHUB_ACTOR}}'
      # git config --global user.email '${{env.GITHUB_ACTOR}}@users.noreply.github.com'
      # git config -l
      # git branch -a
      # ssh-keygen -t rsa -f ~/.ssh/id_rsa_gitHub -q -N github_pass_phrase_aiueo
      # ssh -T git@github.com
      #git remote add origin git@github.com:miquolone/test.git
#        env:
#          GIT_REPOSITORY: 'miquolone/test'
