name: CI_B

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:

  build_create_new_branch_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17, 16 ]

    steps:
      - name: Create new branch
        env:
          GIT_TOKEN: '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'
          GITHUB_TOKEN: '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'
          GITHUB_ACTOR: 'miquolone'
          GIT_REPOSITORY: 'miquolone/test'
        run: |
          git config --global user.name '${{env.GITHUB_ACTOR}}'
          git config --global user.email '${{env.GITHUB_ACTOR}}@users.noreply.github.com'
          git switch -c release/ABC_${{ env.CURRENT_DATETIME }}_first
          git add -A && git commit -m 'abc' --allow-empty
          git push origin release/ABC_${{ env.CURRENT_DATETIME }}_first

      - name: Create new branch Type 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Mona Lisa"
          git switch -c release/ABC_${{ env.CURRENT_DATETIME }}_second
          git branch -a
          git config -l
          git push origin release/ABC_${{ env.CURRENT_DATETIME }}_second

      # ssh-keygen -t rsa -f ~/.ssh/id_rsa_gitHub -q -N github_pass_phrase_aiueo
      # ls ~/.ssh/
      # echo ~/.git/config
      # git rm --cached test
      # git clone https://miquolone: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@github.com/miquolone/test
      # cd test
      # git remote set-url origin https://miquolone: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@github.com/miquolone/test
      # git clone https://${env.GITHUB_ACTOR}:${GIT_TOKEN}@github.com/${GIT_REPOSITORY}
      # git config -l
      # git branch -a
      # ssh-keygen -t rsa -f ~/.ssh/id_rsa_gitHub -q -N github_pass_phrase_aiueo
      # ssh -T git@github.com
      #git remote add origin git@github.com:miquolone/test.git
