## Printするだけ

name: print-tag

on:
  workflow_call:

jobs:

  print-tag:
    strategy:
      matrix:
        node: [ 16 ]

    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        run: |
          echo  The tag is ${{ github.event.inputs.tag }}
          echo ${{ secrets.KEY }}
          echo ${{ secrets.actions}}
          echo "$SUPER_SECRET"
          echo Hello, world!
